version: "3.8"

services: 
  devenv:
    container_name: dailyworks-devenv
    hostname: devenv
    build: .
    environment: 
      - CHROME_BIN='/usr/bin/chromium-browser'
    ports: 
      - 3000:3000
      - 4200:4200
    volumes: 
      - ./:/usr/src
    tty: true
